BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            id: miles_input
            text: "0"

        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "up"
            Button
                text: "down"

    Button:
        text: "Convert miles to Km"
        on_press: app.handle_convert()

    Label:
        text: f"{app.output_km}"
